defaults:
  - _self_
  - tasks: merlin_image_hand_cond

name: train_diffusion_merlin_image_hand_cond_dinov2_${num_inference_steps}
_target_: diffusion_policy.unet.train_unet_image_policy.TrainDiffusionUnetImageWorkspace

device: "cuda:0"

task_name: ${tasks.name}
shape_meta: ${tasks.shape_meta}
exp_name: "hand_cond_dinov2"

# This should be changed?
horizon: 16
num_obs_steps: 1
num_action_steps: 8
num_inference_steps: 100
num_latency_steps: 0
dataset_obs_steps: ${num_obs_steps}
past_action_visible: False
keypoint_visible_rate: 1.0
global_obs_cond: True

policy:
  _target_: diffusion_policy.unet.unet_image_policy.DiffusionUnetImagePolicy

  shape_meta: ${shape_meta}

  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    num_train_timesteps: 100
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    variance_type: fixed_small
    clip_sample: True
    prediction_type: epsilon

  obs_encoder:
    _target_: shared.vision.common.multi_image_obs_encoder.ObsEncoder
    shape_meta: ${shape_meta}
    vision_backbone:
      _target_: shared.vision.dinov2.model_getter.get_dinov2
      name: dinov2_vits14
      pretrained: True
      output: cls
      proj_dim: null
    resize_shape: [240, 240]
    crop_shape: [224, 224]
    random_crop: True
    color_jitter:
      brightness: 0.64
      contrast: 0.32
      saturation: 0.32
      hue: 0.08
      p: 0.8
    use_group_norm: False
    share_vision_backbone: True
    imagenet_norm: True # don't think this will do anything

  horizon: ${horizon}
  num_action_steps: ${eval:'${num_action_steps}+${num_latency_steps}'}
  num_obs_steps: ${num_obs_steps}
  num_inference_steps: ${num_inference_steps}
  global_obs_cond: ${global_obs_cond}
  embed_dim_D: 128
  down_dims: [512, 1024, 2048]
  kernel_size: 5
  num_groups: 8
  film_modulation_scale: True

ema:
  _target_: shared.models.unet.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: 256
  num_workers: 4
  shuffle: True
  pin_memory: True
  persistent_workers: False

val_dataloader:
  batch_size: 256
  num_workers: 4
  shuffle: False
  pin_memory: True
  persistent_workers: False

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: ${device}
  seed: 42
  debug: False
  resume: False
  lr_scheduler: cosine
  lr_warmup_steps: 500
  num_epochs: 5000
  gradient_accumulate_every: 1
  use_ema: True
  freeze_encoder: False
  rollout_every: 50
  checkpoint_every: 50
  val_every: 1
  sample_every: 5
  max_train_steps: null
  max_val_steps: null
  tqdm_interval_sec: 1.0

logging:
  project: diffusion_policies
  resume: True
  mode: offline
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: train_loss
    mode: min
    k: 5
    format_str: 'epoch={epoch:04d}-train_loss={train_loss:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}
